
all:rgen a2-ece650 a3-ece650

rgen:rgen.c
	gcc -o rgen rgen.c

a2-ece650:a2-ece650.c
	gcc -o a2-ece650 a2-ece650.c

a3-ece650:a3-ece650.c
	gcc -o a3-ece650 a3-ece650.c

clean:
	rm -rf *o rgen a2-ece650 a3-ece650
